import type { SiteDictionary } from './types'

export const en = {
  metadata: {
    title: 'Oz Avrahami | Digital Products & Software Systems',
    description: 'I design and build websites, applications, custom software and automation systems that help businesses work smarter, save time and grow.',
  },
  identity: {
    name: 'Oz Avrahami',
    portraitLabel: 'professional portrait',
  },
  navigation: {
    work: 'Work',
    services: 'Services',
    process: 'Process',
    about: 'About',
    contact: 'Contact',
  },
  header: {
    contactCta: "Let's talk",
    menuLabel: 'Menu',
    closeMenuLabel: 'Close menu',
    languageLabel: 'Language selection',
    hebrewLabel: 'עברית',
    englishShortLabel: 'EN',
    englishLongLabel: 'English',
  },
  hero: {
    availability: 'Taking on new projects',
    titleLead: 'Digital products. Business systems.',
    titleAccent: 'Built around your business.',
    description: 'I design and build websites, applications, custom software and automation systems that help businesses work smarter, save time and grow.',
    primaryCta: 'Start a project',
    secondaryCta: 'View my work',
    primaryCapability: {
      value: 'Web · Mobile',
      label: 'Apps & systems',
    },
    secondaryCapability: {
      value: 'Automation · AI',
      label: 'Smart workflows',
    },
  },
  capabilityMarquee: {
    websites: 'Websites',
    businessSystems: 'Business systems',
    applications: 'Applications',
    customSoftware: 'Custom software',
    automation: 'Automation',
    integrations: 'Integrations',
    ai: 'AI',
  },
  services: {
    kicker: 'Services',
    title: 'Technology built around your business.',
    description: 'Every business is different, so the technology should fit the way you work — not the other way around. I build the solution around your real need.',
    items: {
      websites: {
        number: '01',
        title: 'Websites & digital experiences',
        description: 'Fast, modern, precise websites built around your business goals — from brochure sites and landing pages to complex web platforms.',
      },
      businessSystems: {
        number: '02',
        title: 'Business systems',
        description: 'Management systems, dashboards, portals and internal tools that bring processes and information into one place.',
      },
      applications: {
        number: '03',
        title: 'Applications & software',
        description: 'Web and mobile applications and custom software built around your needs and workflows.',
      },
      automation: {
        number: '04',
        title: 'Automation & integrations',
        description: 'Connecting systems and services, working with APIs and automating manual, repetitive processes to save time and reduce errors.',
      },
      ai: {
        number: '05',
        title: 'AI solutions',
        description: 'Embedding AI into existing systems and processes to streamline work, analyze information and build smart tools that fit your business.',
      },
    },
  },
  work: {
    kicker: 'Work',
    title: 'Selected projects.',
    description: 'Systems and products built from a real need — from idea to working product.',
    lead: "I don't just build websites — I build real products and software systems.",
    projects: {
      financeTracker: {
        number: '01',
        title: 'Finance Tracker',
        category: 'Financial management platform',
        description: 'A comprehensive financial platform that brings transactions, budgets, loans, investments, assets and liabilities into one place — with dashboards, automatic calculations and a clear financial picture.',
        tags: ['WEB APP', 'FINTECH', 'DASHBOARD', 'AUTOMATION', 'INTEGRATIONS'],
      },
      tradingJournal: {
        number: '02',
        title: 'Trading Journal',
        category: 'Trading analytics & journaling',
        description: 'A platform for traders that centralizes trades, performance, analysis, a journal and rules — making it clear what works, where mistakes happen and how to improve over time.',
        tags: ['TRADING', 'ANALYTICS', 'WEB APP', 'DATA', 'INTEGRATIONS'],
      },
      lifeOs: {
        number: '03',
        title: 'LifeOS',
        category: 'Daily planning & productivity app',
        description: 'A mobile-first app that turns tasks and weekly planning into a simple, clear flow — from quick capture through planning, execution and completion.',
        tags: ['MOBILE', 'PRODUCTIVITY', 'APP', 'UX', 'PRODUCT DESIGN'],
      },
      tradeGuard: {
        number: '04',
        title: 'TradeGuard',
        category: 'Trading discipline software & automation',
        description: "Desktop software that connects a trader's risk rules to their trading environment, turning manual limits into an enforceable technical mechanism.",
        tags: ['DESKTOP', 'AUTOMATION', 'TRADING', 'SOFTWARE', 'INTEGRATIONS'],
      },
    },
  },
  process: {
    kicker: 'Process',
    title: 'From idea to working product.',
    description: 'One process that connects the business need, the user experience and the technology.',
    items: {
      understand: {
        number: '01',
        title: 'Understand',
        description: 'We start from the business, not the technology — understanding the need, the users and the existing process before choosing a solution.',
      },
      define: {
        number: '02',
        title: 'Define',
        description: 'We define the product, the user experience and the right technical solution.',
      },
      build: {
        number: '03',
        title: 'Build',
        description: 'We turn the plan into a real product with modern technology, quality code and an organized development process.',
      },
      launch: {
        number: '04',
        title: 'Launch & improve',
        description: 'We go live, test real usage and keep improving as needed.',
      },
    },
  },
  whyWorkWithMe: {
    kicker: 'Why work with me',
    titleLead: 'Fewer layers.',
    titleAccent: 'More building.',
    description: 'One technology partner, from concept to product. No middlemen, no management layers — directly with the person who builds.',
    items: {
      direct: 'You talk directly to the person who builds.',
      productThinking: 'Not just development — thinking about the product and the business.',
      workflowFit: 'A solution that fits your process, not the other way around.',
      endToEnd: 'Support from the idea stage all the way to launch.',
    },
  },
  technology: {
    kicker: 'Technology',
    title: 'Built with modern technology.',
    description: 'The tools are a means, not the goal. I choose the technology that fits the project — so the result is fast, stable and easy to maintain.',
    items: ['React', 'Next.js', 'Node.js', 'TypeScript', 'JavaScript', 'Python', 'PostgreSQL', 'Supabase', 'APIs', 'Cloud', 'AI', 'Mobile', 'Automation'],
  },
  about: {
    kicker: 'About',
    title: 'Nice to meet you.',
    body: "I build digital products and software systems — not just websites. I've worked on management systems, data-driven platforms, mobile apps and desktop software, always with the same approach: understand the business problem first, then choose the technology. I'm involved directly at every stage — from scoping to launch — connecting what the business needs with what's possible to build.",
    principles: {
      productThinking: {
        title: 'Product thinking',
        description: 'Not just code — understanding the product and the problem it solves.',
      },
      businessSystems: {
        title: 'Business systems',
        description: 'Experience building complex tools, systems and digital processes.',
      },
      technologyAndBusiness: {
        title: 'Technology + business',
        description: 'Technical decisions that start from the business need.',
      },
      directCollaboration: {
        title: 'Direct collaboration',
        description: 'Direct communication through planning, development and launch.',
      },
    },
  },
  contact: {
    titleLead: 'Have an idea?',
    titleAccent: "Let's build it.",
    description: "Tell me what you want to build, improve or automate — and we'll figure out how to turn it into a solution that works.",
    form: {
      nameLabel: 'Name',
      namePlaceholder: 'Full name',
      contactLabel: 'How should I get back to you?',
      contactPlaceholder: 'Phone or email',
      messageLabel: 'What would you like to build?',
      messagePlaceholder: 'Tell me briefly about the website, system, app or process you want to improve...',
      submitLabel: 'Send project details',
      reassurance: "No commitment. We'll talk, understand the need and see if we're a good fit.",
      successMessage: "Thanks! I've got your details and will get back to you soon.",
      errorMessage: null,
    },
  },
  footer: {
    positioning: 'I design and build digital products, software systems and automation for businesses.',
    navigationTitle: 'Navigation',
    servicesTitle: 'Services',
    connectTitle: 'Connect',
    serviceLabels: ['Websites', 'Applications', 'Business systems', 'Software', 'Automation', 'AI'],
    socialLabels: {
      email: 'Email',
      linkedIn: 'LinkedIn',
      github: 'GitHub',
    },
    unavailableLabel: 'Coming soon',
    copyright: '© 2026 Oz Avrahami. All rights reserved.',
  },
  mockups: {
    sampleLabel: 'Sample',
    automation: {
      source: 'Form',
      target: 'CRM',
    },
    lifeOs: {
      today: 'Today',
      weeklyPlan: 'Weekly plan',
      clientCall: 'Client call',
      weeklyPlanning: 'Weekly planning',
      scopingCall: 'Scoping call',
      writeDocument: 'Write document',
      reviewBuild: 'Review build',
      sunday: 'Sun',
      monday: 'Mon',
      tuesday: 'Tue',
    },
    finance: {
      totalAssets: 'Total assets',
      income: 'Income',
      monthlyIncome: 'Monthly income',
      portfolio: 'Portfolio',
      monthlyCashFlow: 'Monthly cash flow',
      liabilities: 'Liabilities',
      incomeRow: 'Income',
      expenseRow: 'Expense',
      overview: 'Overview',
      transactions: 'Transactions',
      investments: 'Investments',
      loans: 'Loans',
      reports: 'Reports',
    },
    trading: {
      winRate: 'Win rate',
      profitFactor: 'Profit factor',
      totalTrades: 'Total trades',
      cumulative: 'Cumulative',
      equityCurve: 'Equity curve',
      recentTrades: 'Recent trades',
      long: 'Long',
      short: 'Short',
      assetA: 'Asset A',
      assetB: 'Asset B',
      assetC: 'Asset C',
      assetD: 'Asset D',
    },
    tradeGuard: {
      protectionActive: 'Protection active',
      connected: 'Connected',
      maximumDailyLoss: 'Max daily loss',
      maximumTrades: 'Max trades',
      automaticEnforcement: 'Auto-enforcement',
      set: 'Set',
      active: 'Active',
    },
  },
} as const satisfies SiteDictionary
