// Approved bilingual copy from design/oz-digital-flow-design/site/app.js.
// The reference's demo submission strings are not used by the real contact form.
export const flowCopy = {he:{
 skip:'דלגו לתוכן',name:'עוז אברהמי',nav:['שירותים','כלים ומערכות','נעים להכיר','שאלות ותשובות'],talk:'בואו נדבר',language:'Switch to English',menu:'פתיחת תפריט',closeMenu:'סגירת תפריט',
 eyebrow:'אתרים, אוטומציות ופתרונות AI לעסקים',headline:'יותר זמן לעסק.<br>יותר מקום<br class="hero-break"> <span class="hero-accent">לצמוח.</span>',
 description:'אני עוזר לעסקים לבנות נוכחות דיגיטלית טובה יותר, לחבר בין המערכות ולהפוך עבודה ידנית לזמן פנוי.',heroCta:'נדבר על העסק שלכם',seeServices:'איך אפשר לעזור?',note:'שיחה קצרה, בלי התחייבות.',
 sceneTitle:'כל המערכות. באותו כיוון.',sceneDemo:'המחשה',motionPause:'השהיית תנועה',motionResume:'הפעלת תנועה',newLead:'פנייה חדשה מהאתר',leadName:'דנה לוי',leadDetail:'מתעניינת בשירות',leadTag:'התקבלה עכשיו',yourSite:'העסק שלכם.<br><span>במקום הנכון.</span>',miniCta:'בואו נדבר',autoReply:'המענה כבר בדרך',replyText:'״היי דנה, תודה שפנית!<br>קיבלנו את הפרטים ונהיה בקשר.״',crm:'מערכת הלקוחות',crmDetail:'פרטי הפנייה נשמרו',crmTag:'הכול מסונכרן',aiLabel:'אוטומציה + AI',connected:'חיבור שעובד',run:'הפעילו את התהליך',runAgain:'הפעילו שוב',runHint:'לחצו ותראו איך זה עובד',flowSteps:['פנייה חדשה נכנסת מהאתר','הפרטים עוברים למקום הנכון','הלקוחה מקבלת מענה ראשוני','הכול מתועד. אתם יכולים להמשיך ביום שלכם.'],
 heroTags:['מותאם לעסק שלכם','קשר ישיר איתי','מהרעיון ועד ההשקה'],scroll:'יש עוד בהמשך',trusted:'כלים מוכרים.<br>אפשרויות חדשות.',
 servicesLabel:'מה אפשר לעשות יחד',servicesTitle:'העסק מתקדם.<br>הטכנולוגיה איתו.',servicesIntro:'מהאתר שהלקוחות רואים ועד לתהליכים שמאחורי הקלעים. פתרונות שמתחברים לדרך שבה אתם עובדים.',
 services:[
 ['globe','אתרים וחנויות אונליין','אתר שנראה מצוין, מסביר בדיוק מה אתם מציעים ומקל על הלקוחות לפנות או לקנות.','אתרי תדמית · דפי נחיתה · חנויות אונליין'],
 ['bolt','אוטומציות וחיבור מערכות','פניות, הזמנות, מסמכים ועדכונים. מחברים את הכלים שלכם כדי שהמידע יעבור והעבודה תתקדם.','פחות פעולות ידניות. יותר סדר.'],
 ['spark','AI שעובד בשבילכם','עזרה בטיפול בפניות, סיכום מידע ועיבוד מסמכים — עם בינה מלאכותית שמשתלבת בתהליך שלכם.','פתרונות לצורך אמיתי'],
 ['layers','מערכות בהתאמה אישית','כלי ניהול, פורטל או סביבת עבודה שמרכזים את מה שחשוב לעסק במקום אחד.','בנוי סביב הדרך שלכם'],
 ['app','אפליקציות וכלי עבודה','רעיון לכלי שיקל על הצוות או ישרת את הלקוחות? נהפוך אותו למוצר נוח ושימושי.','מהרעיון למוצר עובד']
 ],webMini:'הסיפור שלכם.<br>האתר שלכם.',webMiniSmall:'נבנה סביב המטרות של העסק',autoLabels:['פנייה נכנסת','אוטומציה','מענה ללקוח'],
 toolsLabel:'מבחר מארגז הכלים שלי',toolsTitle:'כלים שאתם מכירים.<br>חיבורים שעושים הבדל.',toolsIntro:'הפתרון הנכון יכול להתחיל בכלים שכבר יש לכם. מחברים, מתאימים ומשלימים את מה שחסר.',toolsNote:'אלה רק חלק מהכלים שאני עובד איתם. לכל עסק בוחרים את השילוב שמתאים לו, ומשלבים פיתוח מותאם כשצריך.',toolsSecondaryTitle:'ענן, תשתיות ומערכות ארגוניות',toolsSecondaryDescriptions:['סביבות פיתוח והרצת יישומים','שירותי ענן ותשתיות','ניהול לקוחות ותהליכים עסקיים'],toolDescriptions:['חנויות אונליין','חנויות על בסיס WordPress','אתרים וניהול תוכן','אתרים לעסקים','אוטומציות וחיבור מערכות','תהליכי עבודה אוטומטיים','חיבורים בין אפליקציות','ניהול עבודה וצוותים','בינה מלאכותית ושפה','AI לכתיבה, ניתוח ופיתוח','פיתוח כלים ועיבוד נתונים','עיצוב ובניית עמודים','תקשורת עם לקוחות','קבצים ועבודה משותפת','ידע, מסמכים ותכנון','נתונים ומערכות עבודה'],
 aboutLabel:'נעים להכיר',aboutTitle:'ניסיון במערכות גדולות.<br>יחס אישי לעסק שלכם.',aboutLead:'אני עוז אברהמי. מפתח ומוביל צוותי פיתוח, עם יותר מ־9 שנות ניסיון במערכות עסקיות ובחיבור בין טכנולוגיה לאנשים.',aboutBody:'בעבודתי במטריקס, עבור יוניון מוטורס, הובלתי צוות של חמישה מפתחים ובניית מערכות לניהול לקוחות, תמחור, שיווק והזמנות — מהבנת הצורך ועד העלייה לאוויר.',aboutEnd:'את הניסיון הזה אני מביא לעסק שלכם: הבנה של התהליכים, חשיבה על התמונה המלאה ויכולת לחבר את כל החלקים לפתרון שעובד. לאורך הדרך אתם עובדים ישירות איתי.',aboutPill1:'ממערכות ארגוניות לעסק שלכם.',aboutPill2:'מדברים עם מי שמוביל ובונה.',aboutRole:'פיתוח, אינטגרציות והובלת פתרונות',aboutLink:'נכיר גם בלינקדאין',aboutProof:[['9+','שנות ניסיון במערכות עסקיות'],['5','מפתחים בצוות שהובלתי']],
 processTitle:'מתחילים בשיחה. מתקדמים יחד.',processIntro:'תהליך ברור, עם מקום לשאלות בכל שלב.',process:[['מכירים את העסק','מבינים מה עובד, מה מעכב ומה הייתם רוצים לשפר.'],['בוחרים כיוון','מגדירים תכולה, פתרון והצעת מחיר מסודרת.'],['בונים ומדייקים','מתקדמים עם עדכונים ומקום למשוב שלכם.'],['יוצאים לדרך','בודקים, משיקים ומוודאים שאתם יודעים לעבוד עם הפתרון.']],
 faqLabel:'טוב ששאלתם',faqTitle:'קצת פחות סימני שאלה.<br>קצת יותר בהירות.',faqIntro:'כמה דברים שכדאי לדעת לפני שמתחילים.',faqContact:'יש לכם שאלה אחרת? דברו איתי',faqs:[
 ['מאיפה בכלל מתחילים?','משיחה על העסק שלכם. נבין מה אתם רוצים להשיג, מה כבר קיים ואיפה אפשר לשפר. משם נגדיר יחד את ההיקף ואת הצעד הבא.'],
 ['אפשר לשפר אתר או מערכת קיימים?','כן. נבדוק את מה שכבר יש, את המגבלות ואת המטרה. לפעמים שיפור ממוקד או חיבור נכון בין מערכות מספיקים כדי לפתור את הצורך.'],
 ['כמה זה עולה וכמה זמן זה לוקח?','זה תלוי בתכולה, במורכבות ובחיבורים הנדרשים. אחרי שנבין את הצורך, תקבלו הצעת מחיר ולוח זמנים שמותאמים לעבודה, לפני שמתחילים.'],
 ['מה אוטומציה יכולה לעשות בעסק שלי?','למשל, להעביר פנייה מהאתר למערכת הלקוחות, לשלוח מענה ראשוני, לרכז מסמכים או לעדכן מידע בין כלים. נבחר תהליך שחוזר על עצמו ונבדוק איך אפשר לייעל אותו.'],
 ['צריך ידע טכני כדי להשתמש בפתרון?','המטרה היא שתוכלו לעבוד איתו בנוחות. מתכננים את הממשק ואת התהליך בהתאם למשתמשים, ובמסירה עוברים יחד על מה שצריך לדעת.'],
 ['מה קורה אחרי שהאתר או המערכת עולים לאוויר?','מגדירים מראש מה כלול במסירה ובתמיכה, ומה דורש תחזוקה שוטפת. אפשר לתאם גם המשך ליווי ושיפורים בהתאם לצורך.']
 ],
 contactLabel:'הצעד הבא',contactTitle:'יש לכם משהו<br>שהייתם רוצים שיקרה?',contactBody:'אתר חדש, תהליך שגוזל זמן או רעיון שמחכה לצאת לדרך. ספרו לי עליו ונחשוב יחד איך להתקדם.',whatsapp:'אפשר גם בוואטסאפ',contactName:'איך קוראים לכם?',contactNamePh:'השם שלכם',contactReturn:'איך חוזרים אליכם?',contactReturnPh:'מייל או טלפון',contactMessage:'מה הייתם רוצים לשפר או לבנות?',contactMessagePh:'כמה מילים על העסק ועל הרעיון…',contactSubmit:'ממשיכים למייל',contactHint:'הפרטים ייפתחו בטיוטת מייל שתוכלו לשלוח.',contactReady:'פתחנו בקשה ליצירת טיוטה באפליקציית המייל. ההודעה תישלח רק לאחר שתשלחו אותה משם.',contactSubject:'בואו נדבר על העסק שלי',
 footerDesc:'אתרים, אוטומציות ופתרונות AI.<br>טכנולוגיה שמקדמת את העסק.',footerGuides:'מדריכים',rights:'כל הזכויות שמורות.',float:'נדבר בוואטסאפ',backTop:'חזרה למעלה',accessibility:'אפשרויות נגישות',accessibilityTitle:'תצוגה שנוחה לכם',accessibilityIntro:'התאימו את התנועה והצבעים לנוחות שלכם.',closeAccessibility:'סגירת אפשרויות נגישות',reduceMotion:'עצירת תנועה',reduceMotionHint:'עצירת האנימציות והגלילה החלקה',highContrast:'ניגודיות מוגברת',highContrastHint:'הדגשת טקסט, גבולות וקישורים',accessibilityStatement:'הצהרת נגישות',accessibilityHelp:'אפשר לנווט עם Tab ולהפעיל כפתורים עם Enter או רווח. להגדלת התצוגה השתמשו בהגדרות הזום בדפדפן.',accessibilityReset:'איפוס העדפות'
},en:{
 skip:'Skip to content',name:'Oz Avrahami',nav:['Services','Tools & systems','About me','Questions'],talk:'Let’s talk',language:'מעבר לעברית',menu:'Open menu',closeMenu:'Close menu',
 eyebrow:'Websites, automation & AI for business',headline:'More time.<br>More room<br class="hero-break"> <span class="hero-accent">to grow.</span>',description:'I help businesses build a better digital presence, connect their systems, and turn repetitive work into time well spent.',heroCta:'Let’s talk about your business',seeServices:'How I can help',note:'A short conversation. No commitment.',
 sceneTitle:'Your systems. Working together.',sceneDemo:'Example workflow',motionPause:'Pause motion',motionResume:'Resume motion',newLead:'A new website enquiry',leadName:'Dana Levi',leadDetail:'Interested in your service',leadTag:'Just received',yourSite:'Your business.<br><span>In the right place.</span>',miniCta:'Let’s talk',autoReply:'The reply is on its way',replyText:'“Hi Dana, thanks for reaching out!<br>We have your details and will be in touch.”',crm:'Customer workspace',crmDetail:'Enquiry details saved',crmTag:'Everything is in sync',aiLabel:'AUTOMATION + AI',connected:'Connected by design',run:'Run the workflow',runAgain:'Play it again',runHint:'See it in action',flowSteps:['A new enquiry arrives from the website','Details go to the right place','Your customer gets an initial reply','Everything is recorded. Back to your day.'],
 heroTags:['Made for your business','Work directly with me','From idea to launch'],scroll:'More below',trusted:'Familiar tools.<br>New possibilities.',
 servicesLabel:'What we can build together',servicesTitle:'Your next step.<br>Made possible.',servicesIntro:'From the website your customers see to the work behind the scenes. Solutions that fit how you work.',
 services:[['globe','Websites & online stores','A website that looks great, makes your offer clear, and helps customers get in touch or make a purchase.','Business websites · Landing pages · Online stores'],['bolt','Automation & integrations','Enquiries, orders, documents, and updates. Connect your tools so information flows and work moves forward.','Fewer repetitive tasks. More clarity.'],['spark','AI with a purpose','Handle enquiries, summarize information, and process documents with AI that fits into your workflow.','Built around a real need'],['layers','Custom business systems','Management tools, portals, and workspaces that bring your essential information together.','Built around how you work'],['app','Apps & practical tools','An idea that could help your team or your customers? Let’s turn it into something useful.','From idea to working product']],webMini:'Your story.<br>Your website.',webMiniSmall:'Built around your business goals',autoLabels:['New enquiry','Automation','Customer reply'],
 toolsLabel:'A selection from my toolkit',toolsTitle:'Tools you know.<br>Connections that matter.',toolsIntro:'The right solution can start with the tools you already have. Connect, adapt, and fill in the gaps.',toolsNote:'These are just some of the tools I work with. The right mix is chosen for your business, with custom development where it helps.',toolsSecondaryTitle:'Cloud, infrastructure & business systems',toolsSecondaryDescriptions:['Development & app environments','Cloud services & infrastructure','Customer & business management'],toolDescriptions:['Online stores','Stores built on WordPress','Websites & content','Business websites','Automation & integrations','Automated workflows','App integrations','Work & team management','AI & language models','AI for writing, analysis & code','Custom tools & data processing','Page design & building','Customer communication','Files & collaboration','Knowledge, docs & planning','Data & business workspaces'],
 aboutLabel:'Good to meet you',aboutTitle:'Proven experience.<br>Personal commitment.',aboutLead:'I’m Oz Avrahami, a developer and development team lead with 9+ years of experience in business systems, connecting technology with the people who use it.',aboutBody:'At Matrix, working with Union Motors, I led a team of five developers and the delivery of customer management, pricing, marketing, and ordering systems — from understanding the need to launch.',aboutEnd:'I bring that experience to your business: understanding the workflow, seeing the whole picture, and connecting the pieces into a working solution. You work directly with me throughout.',aboutPill1:'Enterprise experience. For your business.',aboutPill2:'Talk to the person leading the work.',aboutRole:'Development, integrations & delivery',aboutLink:'Find me on LinkedIn',aboutProof:[['9+','Years in business systems'],['5','Developers on the team I led']],
 processTitle:'A conversation. Then a clear path.',processIntro:'A straightforward process, with room for questions.',process:[['Understand','Explore what works, what slows you down, and what could improve.'],['Plan','Define the scope, the approach, and a clear proposal.'],['Build & refine','Stay in the loop with updates and room for your feedback.'],['Launch','Test, launch, and make sure you feel comfortable using it.']],
 faqLabel:'Good questions',faqTitle:'Fewer question marks.<br>A clearer way forward.',faqIntro:'A few things worth knowing before we start.',faqContact:'Have another question? Let’s talk',faqs:[['Where do we start?','With a conversation about your business: what you want to achieve, what already exists, and what could work better. Then we define the scope and next steps together.'],['Can you improve an existing website or system?','Yes. We review what you already have, its limitations, and your goals. Sometimes a focused improvement or the right integration is enough.'],['How much does it cost, and how long does it take?','That depends on the scope, complexity, and integrations involved. Once we understand the need, you receive a tailored proposal and timeline before work begins.'],['What can automation do for my business?','For example, move website enquiries into your customer system, send an initial reply, organize documents, or update information between tools. We start with a recurring task and explore how to improve it.'],['Do I need technical skills to use it?','The aim is to make it comfortable to use. The interface and workflow are designed around the people using them, and we walk through everything you need at handover.'],['What happens after launch?','We agree in advance on handover, support, and ongoing maintenance. Continued support and improvements can be arranged around your needs.']],
 contactLabel:'Your next step',contactTitle:'What would you<br>like to make happen?',contactBody:'A new website, a time-consuming process, or an idea waiting to take shape. Tell me about it and we’ll explore the next step.',whatsapp:'Or chat on WhatsApp',contactName:'Your name',contactNamePh:'What should I call you?',contactReturn:'How can I reach you?',contactReturnPh:'Email or phone',contactMessage:'What would you like to improve or build?',contactMessagePh:'A little about your business and your idea…',contactSubmit:'Continue to email',contactHint:'Your details will open in an email draft for you to send.',contactReady:'An email draft has been requested in your email app. Your message will only be sent when you send it there.',contactSubject:'Let’s talk about my business',
 footerDesc:'Websites, automation & AI.<br>Technology that moves business forward.',footerGuides:'Guides',rights:'All rights reserved.',float:'Let’s chat',backTop:'Back to top',accessibility:'Accessibility options',accessibilityTitle:'Make yourself comfortable',accessibilityIntro:'Adjust motion and colors to suit you.',closeAccessibility:'Close accessibility options',reduceMotion:'Pause motion',reduceMotionHint:'Stop animations and smooth scrolling',highContrast:'Higher contrast',highContrastHint:'Emphasize text, borders, and links',accessibilityStatement:'Accessibility statement',accessibilityHelp:'Navigate with Tab and activate buttons with Enter or Space. Use your browser’s zoom settings to enlarge the page.',accessibilityReset:'Reset preferences'
}}
export type FlowCopy = typeof flowCopy.he
export const toolList=[['shopify','Shopify'],['woocommerce','WooCommerce'],['wordpress','WordPress'],['wix','Wix'],['make','Make'],['n8n','n8n'],['zapier','Zapier'],['mondaydotcom','monday.com'],['openai','OpenAI'],['claude','Claude'],['python','Python'],['elementor','Elementor'],['whatsapp','WhatsApp'],['googledrive','Google Drive'],['notion','Notion'],['airtable','Airtable']];
export const secondaryTools=[['docker','Docker'],['aws','AWS'],['dynamics','Microsoft Dynamics']];

export const flowNavigation = ['services', 'tools', 'about', 'faq'] as const
