import type { SiteDictionary } from './types'

export const he = {
  metadata: {
    title: 'עוז אברהמי | מוצרים דיגיטליים ומערכות תוכנה',
    description: 'תכנון ופיתוח אתרי אינטרנט, אפליקציות, מערכות תוכנה ואוטומציות שעוזרות לעסקים לעבוד חכם יותר, לחסוך זמן ולצמוח.',
  },
  identity: {
    name: 'עוז אברהמי',
    portraitLabel: 'דיוקן מקצועי · portrait',
  },
  navigation: {
    work: 'עבודות',
    services: 'שירותים',
    process: 'תהליך העבודה',
    about: 'אודות',
    contact: 'יצירת קשר',
  },
  header: {
    contactCta: 'בואו נדבר',
    menuLabel: 'תפריט',
    closeMenuLabel: 'סגירת תפריט',
    languageLabel: 'בחירת שפה',
  },
  hero: {
    availability: 'מקבל פרויקטים חדשים',
    titleLead: 'טכנולוגיה שבנויה',
    titleAccent: 'סביב העסק שלכם.',
    description: 'אני מתכנן ומפתח אתרי אינטרנט, אפליקציות, מערכות תוכנה ואוטומציות שעוזרות לעסקים לעבוד חכם יותר, לחסוך זמן ולצמוח.',
    primaryCta: 'בואו נדבר על הפרויקט',
    secondaryCta: 'לפרויקטים שלי',
    primaryCapability: {
      value: 'Web · Mobile',
      label: 'אפליקציות ומערכות',
    },
    secondaryCapability: {
      value: 'אוטומציה · AI',
      label: 'תהליכים חכמים',
    },
  },
  capabilityMarquee: {
    websites: 'אתרי אינטרנט',
    businessSystems: 'מערכות לעסקים',
    applications: 'אפליקציות',
    customSoftware: 'תוכנה בהתאמה אישית',
    automation: 'אוטומציות',
    integrations: 'אינטגרציות',
    ai: 'AI',
  },
  services: {
    kicker: 'שירותים',
    title: 'טכנולוגיה שבנויה סביב העסק שלכם.',
    description: 'כל עסק שונה, ולכן הטכנולוגיה צריכה להתאים לתהליך העבודה — לא להפך. אני בונה את הפתרון סביב הצורך האמיתי שלכם.',
    items: {
      websites: {
        number: '01',
        title: 'אתרי אינטרנט וחוויות דיגיטליות',
        description: 'אתרים מהירים, מודרניים ומדויקים שנבנים סביב המטרות העסקיות שלכם — מאתרי תדמית ודפי נחיתה ועד אתרים מורכבים ומערכות מבוססות Web.',
      },
      businessSystems: {
        number: '02',
        title: 'מערכות לעסקים',
        description: 'מערכות ניהול, דשבורדים, פורטלים, כלי עבודה פנימיים ומערכות שמרכזות תהליכים ומידע במקום אחד.',
      },
      applications: {
        number: '03',
        title: 'אפליקציות ותוכנה',
        description: 'פיתוח אפליקציות Web ומובייל ותוכנות בהתאמה אישית לצרכים ולתהליכי העבודה של העסק.',
      },
      automation: {
        number: '04',
        title: 'אוטומציות ואינטגרציות',
        description: 'חיבור מערכות ושירותים, עבודה מול APIs ואוטומציה של תהליכים ידניים וחוזרים כדי לחסוך זמן ולצמצם טעויות.',
      },
      ai: {
        number: '05',
        title: 'פתרונות AI',
        description: 'שילוב יכולות AI בתוך מערכות ותהליכים קיימים כדי לייעל עבודה, לנתח מידע וליצור כלים חכמים שמתאימים לעסק.',
      },
    },
  },
  work: {
    kicker: 'עבודות',
    title: 'פרויקטים נבחרים.',
    description: 'מערכות ומוצרים שנבנו מתוך צורך אמיתי — מהרעיון ועד למוצר עובד.',
    lead: 'אני לא רק בונה אתרים — אני בונה מוצרים ומערכות תוכנה אמיתיות.',
    projects: {
      financeTracker: {
        number: '01',
        title: 'Finance Tracker',
        category: 'מערכת לניהול פיננסי',
        description: 'מערכת מקיפה לניהול פיננסי שמרכזת תנועות, תקציבים, הלוואות, השקעות, נכסים והתחייבויות במקום אחד — עם דשבורדים, חישובים אוטומטיים וכלים לקבלת תמונה פיננסית ברורה.',
        tags: ['WEB APP', 'FINTECH', 'DASHBOARD', 'AUTOMATION', 'INTEGRATIONS'],
      },
      tradingJournal: {
        number: '02',
        title: 'Trading Journal',
        category: 'פלטפורמה לניהול וניתוח מסחר',
        description: 'מערכת לסוחרים שמרכזת עסקאות, ביצועים, ניתוחים, יומן מסחר וכללי עבודה — ומאפשרת להבין בצורה ברורה מה עובד, איפה נעשות טעויות ואיך משתפרים לאורך זמן.',
        tags: ['TRADING', 'ANALYTICS', 'WEB APP', 'DATA', 'INTEGRATIONS'],
      },
      lifeOs: {
        number: '03',
        title: 'LifeOS',
        category: 'אפליקציה לתכנון וניהול היום',
        description: 'אפליקציה שנבנתה בגישת Mobile-First כדי להפוך משימות ותכנון שבועי לתהליך פשוט וברור — מהקליטה הראשונית של משימה ועד לתכנון, ביצוע והשלמה.',
        tags: ['MOBILE', 'PRODUCTIVITY', 'APP', 'UX', 'PRODUCT DESIGN'],
      },
      tradeGuard: {
        number: '04',
        title: 'TradeGuard',
        category: 'תוכנה ואוטומציה לניהול משמעת במסחר',
        description: 'מערכת תוכנה שמחברת בין כללי ניהול הסיכון של הסוחר לבין סביבת המסחר שלו, במטרה להפוך כללים והגבלות מתכנון ידני למנגנון טכנולוגי שניתן לאכוף.',
        tags: ['DESKTOP', 'AUTOMATION', 'TRADING', 'SOFTWARE', 'INTEGRATIONS'],
      },
    },
  },
  process: {
    kicker: 'תהליך העבודה',
    title: 'מרעיון למוצר עובד.',
    description: 'תהליך אחד שמחבר בין הצורך העסקי, חוויית המשתמש והטכנולוגיה.',
    items: {
      understand: {
        number: '01',
        title: 'מבינים',
        description: 'מתחילים מהעסק, לא מהטכנולוגיה. מבינים את הצורך, המשתמשים והתהליך הקיים לפני שבוחרים פתרון.',
      },
      define: {
        number: '02',
        title: 'מתכננים',
        description: 'מגדירים את המוצר, חוויית המשתמש והפתרון הטכנולוגי הנכון.',
      },
      build: {
        number: '03',
        title: 'בונים',
        description: 'הופכים את התכנון למוצר אמיתי באמצעות טכנולוגיות מודרניות, קוד איכותי ותהליך פיתוח מסודר.',
      },
      launch: {
        number: '04',
        title: 'משיקים ומשפרים',
        description: 'עולים לאוויר, בודקים שימוש אמיתי וממשיכים לשפר בהתאם לצורך.',
      },
    },
  },
  whyWorkWithMe: {
    kicker: 'למה לעבוד איתי',
    titleLead: 'פחות שכבות.',
    titleAccent: 'יותר עשייה.',
    description: 'שותף טכנולוגי אחד, מהרעיון ועד המוצר. בלי מתווכים ובלי שכבות ניהול — ישירות מול מי שבונה.',
    items: {
      direct: 'מדברים ישירות עם מי שבונה.',
      productThinking: 'לא רק פיתוח — חשיבה על המוצר והעסק.',
      workflowFit: 'פתרון שמתאים לתהליך שלכם, לא להפך.',
      endToEnd: 'ליווי משלב הרעיון ועד העלייה לאוויר.',
    },
  },
  technology: {
    kicker: 'טכנולוגיה',
    title: 'נבנה עם טכנולוגיות מודרניות.',
    description: 'הכלים הם אמצעי, לא מטרה. אני בוחר את הטכנולוגיה שמתאימה לפרויקט — כדי שהתוצאה תהיה מהירה, יציבה וקלה לתחזוקה.',
    items: ['React', 'Next.js', 'Node.js', 'TypeScript', 'JavaScript', 'Python', 'PostgreSQL', 'Supabase', 'APIs', 'Cloud', 'AI', 'Mobile', 'Automation'],
  },
  about: {
    kicker: 'אודות',
    title: 'נעים להכיר.',
    body: 'אני בונה מוצרים דיגיטליים ומערכות תוכנה — לא רק אתרים. עבדתי על מערכות ניהול, פלטפורמות מבוססות נתונים, אפליקציות מובייל ותוכנות דסקטופ, ותמיד מתוך אותה גישה: קודם להבין את הבעיה העסקית, ורק אחר כך לבחור את הפתרון הטכנולוגי. אני מעורב ישירות בכל שלב — מהאפיון ועד ההשקה — ומחבר בין מה שהעסק צריך לבין מה שאפשר לבנות.',
    principles: {
      productThinking: {
        title: 'חשיבה מוצרית',
        description: 'לא רק קוד — הבנה של המוצר והבעיה שהוא פותר.',
      },
      businessSystems: {
        title: 'מערכות לעסקים',
        description: 'ניסיון בבניית כלים, מערכות ותהליכים דיגיטליים מורכבים.',
      },
      technologyAndBusiness: {
        title: 'טכנולוגיה + עסק',
        description: 'החלטות טכנולוגיות שמתחילות מהצורך העסקי.',
      },
      directCollaboration: {
        title: 'עבודה ישירה',
        description: 'תקשורת ישירה לאורך התכנון, הפיתוח וההשקה.',
      },
    },
  },
  contact: {
    titleLead: 'יש לכם רעיון?',
    titleAccent: 'בואו נבנה אותו.',
    description: 'ספרו לי מה אתם רוצים לבנות, לשפר או להפוך לאוטומטי — ונבדוק איך אפשר להפוך את זה לפתרון שעובד.',
    form: {
      nameLabel: 'שם',
      namePlaceholder: 'השם המלא',
      contactLabel: 'איך נוח לחזור אליכם?',
      contactPlaceholder: 'טלפון או אימייל',
      messageLabel: 'מה אתם רוצים לבנות?',
      messagePlaceholder: 'ספרו לי בכמה מילים על האתר, המערכת, האפליקציה או התהליך שתרצו לשפר...',
      submitLabel: 'שלחו לי את הפרטים',
      reassurance: 'בלי התחייבות. נדבר, נבין את הצורך ונראה אם זה מתאים.',
      successMessage: 'תודה! קיבלתי את הפרטים ואחזור אליכם בהקדם.',
      errorMessage: null,
    },
  },
  footer: {
    positioning: 'מתכנן ומפתח מוצרים דיגיטליים, מערכות תוכנה ואוטומציות לעסקים.',
    navigationTitle: 'ניווט',
    servicesTitle: 'שירותים',
    connectTitle: 'קשר',
    serviceLabels: ['אתרי אינטרנט', 'אפליקציות', 'מערכות לעסקים', 'תוכנה', 'אוטומציות', 'AI'],
    socialLabels: {
      email: 'Email',
      linkedIn: 'LinkedIn',
      github: 'GitHub',
    },
    unavailableLabel: 'ייווסף בקרוב',
    copyright: '© 2026 עוז אברהמי. כל הזכויות שמורות.',
  },
  mockups: {
    sampleLabel: 'הדגמה',
    automation: {
      source: 'Form',
      target: 'CRM',
    },
    lifeOs: {
      today: 'היום',
      weeklyPlan: 'תכנון שבועי',
      clientCall: 'שיחה עם לקוח',
      weeklyPlanning: 'תכנון שבועי',
      scopingCall: 'שיחת אפיון',
      writeDocument: 'כתיבת מסמך',
      reviewBuild: 'בדיקת גרסה',
      sunday: 'ראשון',
      monday: 'שני',
      tuesday: 'שלישי',
    },
    finance: {
      totalAssets: 'סה״כ נכסים',
      income: 'הכנסות',
      monthlyIncome: 'הכנסות לפי חודש',
      portfolio: 'תיק השקעות',
      monthlyCashFlow: 'תזרים חודשי',
      liabilities: 'התחייבויות',
      incomeRow: 'הכנסה',
      expenseRow: 'הוצאה',
      overview: 'סקירה כללית',
      transactions: 'תנועות',
      investments: 'השקעות',
      loans: 'הלוואות',
      reports: 'דוחות',
    },
    trading: {
      winRate: 'אחוז הצלחה',
      profitFactor: 'יחס רווח/הפסד',
      totalTrades: 'סה״כ עסקאות',
      cumulative: 'רווח מצטבר',
      equityCurve: 'עקומת הון',
      recentTrades: 'עסקאות אחרונות',
      long: 'לונג',
      short: 'שורט',
      assetA: 'נכס A',
      assetB: 'נכס B',
      assetC: 'נכס C',
      assetD: 'נכס D',
    },
    tradeGuard: {
      protectionActive: 'הגנה פעילה',
      connected: 'מחובר לפלטפורמה',
      maximumDailyLoss: 'הפסד יומי מרבי',
      maximumTrades: 'מקסימום עסקאות',
      automaticEnforcement: 'אכיפה אוטומטית',
      set: 'מוגדר',
      active: 'פעיל',
    },
  },
} as const satisfies SiteDictionary
