import type { RevenueDictionary } from './types'

export const revenueEn = {
  services: {
    websites: {
      slug: 'websites',
      metadata: {
        title: 'Business Website Development | Oz Digital',
        description: 'Strategy, design and development for fast business websites, using custom development, WordPress, Wix Studio or the platform that best fits the job.',
      },
      eyebrow: 'Website development',
      title: 'A business website built around what it needs to achieve.',
      lead: 'A good website should explain your value clearly, earn trust and make the next step easy. I plan and build business websites around those goals, then choose the technology that supports them best.',
      primaryCta: 'Discuss a website project',
      secondaryCta: 'Read the website cost guide',
      outcomesTitle: 'What the project is designed to improve',
      outcomes: [
        { title: 'Clear positioning', description: 'Visitors quickly understand what you offer, who it is for and why they should choose you.' },
        { title: 'Qualified enquiries', description: 'Structure, copy and calls to action guide the right visitors toward a useful conversation.' },
        { title: 'A maintainable asset', description: 'The editing experience, hosting and technical stack match the way your team will actually operate.' },
      ],
      capabilitiesTitle: 'From a focused business site to a custom web experience',
      capabilitiesIntro: 'The scope starts with the business need. A project can include the full build or a targeted improvement to an existing site.',
      capabilities: [
        'Discovery, information architecture and conversion-focused page planning',
        'Responsive UX and visual design in the existing brand language',
        'Custom development for distinctive interactions or technical requirements',
        'WordPress builds when flexible content management is the right fit',
        'Wix or Wix Studio builds for teams that benefit from an integrated platform',
        'Performance, accessibility, analytics and technical SEO foundations',
        'Landing pages, integrations, multilingual content and ongoing improvements',
      ],
      technologyTitle: 'The platform follows the project',
      technologyIntro: 'There is no default platform that is right for every business. The decision considers content ownership, design flexibility, integrations, budget, maintenance and how the site may grow.',
      technologies: [
        { name: 'Custom development', description: 'For projects that need high control, strong performance, custom behavior or integration with other systems.' },
        { name: 'WordPress', description: 'Useful for content-rich sites and teams that need a familiar editorial workflow, with hosting and plugins selected carefully.' },
        { name: 'Wix / Wix Studio', description: 'A practical integrated option for many service businesses, especially when simple day-to-day editing matters.', provider: 'wix' },
        { name: 'Elementor', description: 'A visual WordPress layer that can suit editor-led sites when used with a disciplined component and performance approach.', provider: 'elementor' },
        { name: 'Managed hosting', description: 'Hosting is chosen for the platform and operating needs. Hostinger and uPress are examples to evaluate, not automatic defaults.', provider: 'upress' },
      ],
      processTitle: 'A practical path to launch',
      process: [
        { number: '01', title: 'Define the job', description: 'Clarify audiences, business goals, content, constraints and what a successful launch should change.' },
        { number: '02', title: 'Shape the experience', description: 'Plan the page structure, user journeys, messaging and visual direction before committing to implementation.' },
        { number: '03', title: 'Build and connect', description: 'Develop the responsive site, connect forms and systems, and prepare measurement and search foundations.' },
        { number: '04', title: 'Launch and learn', description: 'Test the experience, publish safely and use real feedback and data to guide worthwhile improvements.' },
      ],
      closingTitle: 'Need a new website—or a clear plan for improving the one you have?',
      closingDescription: 'Tell me what the site needs to do for the business. We can identify the right scope and technology from there.',
    },
    ecommerce: {
      slug: 'ecommerce',
      metadata: {
        title: 'E-commerce & Online Store Development | Oz Digital',
        description: 'Online-store development and improvement with Shopify, WooCommerce or Wix, including Israeli payments, shipping, integrations and operations.',
      },
      eyebrow: 'E-commerce development',
      title: 'An online store that works for customers and operations.',
      lead: 'The storefront is only one part of e-commerce. The right solution also handles products, payments, fulfilment, customer communication and the daily work behind every order.',
      primaryCta: 'Discuss an e-commerce project',
      secondaryCta: 'Compare Shopify and WooCommerce',
      outcomesTitle: 'Built around the whole purchase flow',
      outcomes: [
        { title: 'A smoother path to purchase', description: 'Clear product discovery, trustworthy product pages and fewer avoidable checkout obstacles.' },
        { title: 'Reliable local operations', description: 'Payment, invoicing, shipping and notification choices account for how an Israeli business actually fulfils orders.' },
        { title: 'Room to improve', description: 'Analytics, maintainable implementation and sensible integrations make the store easier to evolve after launch.' },
      ],
      capabilitiesTitle: 'New stores and focused improvements',
      capabilitiesIntro: 'The work can start from zero or from a store that already sells but has conversion, speed, integration or operational problems.',
      capabilities: [
        'Platform selection and store architecture',
        'Shopify, WooCommerce and Wix store implementation where suitable',
        'Product, collection, navigation and search experience',
        'Israeli payment gateway and invoicing integrations where supported',
        'Shipping methods, fulfilment rules and third-party service connections',
        'Theme customization, custom components and checkout-adjacent improvements',
        'Migration planning, performance work and existing-store audits',
        'Analytics, product feeds, email flows and operational automation',
      ],
      technologyTitle: 'Choose the operating model, then the platform',
      technologyIntro: 'Platform selection is a business decision. It depends on catalogue complexity, local integrations, content needs, internal skills, ownership preferences and the expected pace of change.',
      technologies: [
        { name: 'Shopify', description: 'A hosted commerce platform with a strong operational core and app ecosystem. It often suits teams that value a managed technical foundation.', provider: 'shopify' },
        { name: 'WooCommerce', description: 'A flexible WordPress commerce stack that offers extensive control, with greater responsibility for hosting, updates and plugin quality.' },
        { name: 'Wix', description: 'Can be a suitable all-in-one choice for smaller catalogues and straightforward operations when its local capabilities fit the requirements.', provider: 'wix' },
        { name: 'Payments and shipping', description: 'Israeli gateways, invoicing systems, couriers and fulfilment services are evaluated against the chosen platform before the build is committed.' },
      ],
      processTitle: 'Commerce decisions before decoration',
      process: [
        { number: '01', title: 'Map the operation', description: 'Understand products, customers, payments, delivery, fulfilment, returns and the people who run the store.' },
        { number: '02', title: 'Select and specify', description: 'Choose the platform and integrations, then define the catalogue, journeys, content and technical boundaries.' },
        { number: '03', title: 'Build and test', description: 'Implement the experience and test real order scenarios across devices, payment states and fulfilment paths.' },
        { number: '04', title: 'Launch and optimize', description: 'Migrate carefully, monitor the first orders and prioritize improvements using customer behavior and operational feedback.' },
      ],
      closingTitle: 'Planning a store or trying to fix one that has become hard to run?',
      closingDescription: 'Share the current setup, catalogue and operational bottlenecks. The first step is choosing the right problem to solve.',
    },
    automation: {
      slug: 'automation',
      metadata: {
        title: 'Business Automation & AI Workflows | Oz Digital',
        description: 'Practical automation for leads, CRM, email, APIs, WhatsApp-compatible workflows and repetitive back-office work, measured by time and errors saved.',
      },
      eyebrow: 'Automation & AI',
      title: 'Remove repeat work from the way your business operates.',
      lead: 'Automation is valuable when it shortens response time, prevents mistakes or gives people back meaningful hours. I connect the systems and steps that currently depend on copying, chasing and remembering.',
      primaryCta: 'Map an automation opportunity',
      secondaryCta: 'See 10 practical automations',
      outcomesTitle: 'Start with a measurable bottleneck',
      outcomes: [
        { title: 'Faster response', description: 'Route leads, tasks and exceptions to the right person without waiting for manual handoffs.' },
        { title: 'Fewer avoidable errors', description: 'Validate and synchronize information instead of repeatedly copying it between disconnected systems.' },
        { title: 'More useful capacity', description: 'Reduce routine administration so the team can spend time on customers, decisions and work that needs judgment.' },
      ],
      capabilitiesTitle: 'Practical workflows, with humans kept in the right places',
      capabilitiesIntro: 'Not every step should be automated. The best workflows automate predictable work, expose exceptions and leave sensitive decisions with people.',
      capabilities: [
        'Lead capture, enrichment, assignment and response workflows',
        'CRM synchronization and lifecycle updates',
        'Email sequences, internal notifications and follow-up reminders',
        'WhatsApp-related flows through approved providers and supported APIs',
        'Make scenarios and custom API integrations',
        'Document, spreadsheet and repetitive back-office processing',
        'AI-assisted classification, extraction, summarization and drafting with review controls',
        'Monitoring, error handling, auditability and maintenance planning',
      ],
      technologyTitle: 'Use the simplest reliable layer',
      technologyIntro: 'A no-code scenario may be enough; a custom service may be safer for complex logic or scale. The choice follows reliability, data sensitivity, API limits and total maintenance cost.',
      technologies: [
        { name: 'Make', description: 'A visual automation platform that works well for many cross-system workflows, especially when the scenario remains observable and maintainable.', provider: 'make' },
        { name: 'APIs and webhooks', description: 'Direct connections for systems with stable interfaces, custom rules or requirements that do not fit a generic connector.' },
        { name: 'AI-assisted steps', description: 'Useful for unstructured inputs such as messages and documents when outputs are constrained, monitored and reviewed where necessary.' },
        { name: 'WhatsApp workflows', description: 'Implemented only through technically appropriate, policy-compliant providers and official capabilities; not through brittle personal-account workarounds.' },
      ],
      processTitle: 'Automate the process, not the confusion',
      process: [
        { number: '01', title: 'Observe', description: 'Map the current process, volumes, time cost, error points, exceptions and system ownership.' },
        { number: '02', title: 'Prioritize', description: 'Estimate the likely saving and risk, then select a focused workflow with a clear success measure.' },
        { number: '03', title: 'Implement safely', description: 'Connect the systems, handle failure paths, protect sensitive data and keep human approval where it matters.' },
        { number: '04', title: 'Measure and refine', description: 'Monitor runs, compare the result with the baseline and improve only where the evidence supports it.' },
      ],
      closingTitle: 'Which recurring task is quietly consuming your week?',
      closingDescription: 'Describe the steps, systems and frequency. We can estimate whether automation is worthwhile before building it.',
    },
  },
  guidesIndex: {
    metadata: {
      title: 'Practical Digital Guides for Businesses | Oz Digital',
      description: 'Clear, useful guides about business websites, e-commerce, automation and choosing technology for an Israeli business.',
    },
    eyebrow: 'Guides',
    title: 'Useful decisions before expensive technology.',
    description: 'Practical, plain-language guides for business owners choosing platforms, planning budgets and improving daily work.',
    readGuideLabel: 'Read guide',
    guideCountLabel: '3 in-depth guides',
  },
  guides: {
    'shopify-vs-woocommerce-israel': {
      slug: 'shopify-vs-woocommerce-israel',
      metadata: {
        title: 'Shopify vs WooCommerce for an Israeli Business | Oz Digital',
        description: 'A practical 2026 comparison of Shopify and WooCommerce for Israeli businesses: costs, payments, Hebrew, operations, control and fit.',
      },
      category: 'E-commerce',
      title: 'Shopify vs WooCommerce — which is better for an Israeli business?',
      description: 'The useful answer is not which platform wins globally, but which operating model creates less friction for your specific store.',
      readingTime: '10 min read',
      publishedLabel: 'Updated September 2026',
      publishedDate: '2026-09-04',
      updatedDate: '2026-09-04',
      intro: [
        'Shopify and WooCommerce can both run a serious Israeli online store. They differ less in the storefront features customers notice and more in who owns the technical work behind hosting, updates, extensions and troubleshooting.',
        'This guide compares the decisions that matter in practice: local payments and invoicing, Hebrew and RTL, shipping, ongoing costs, flexibility, maintenance and the skills available inside the business.',
      ],
      blocks: [
        { type: 'callout', title: 'The short answer', body: 'Choose Shopify when a managed commerce foundation and simpler technical operations are worth more than maximum control. Choose WooCommerce when WordPress fits your content model, you need deeper ownership or customization, and you have reliable technical maintenance.' },
        { type: 'section', id: 'operating-model', title: 'Start with the operating model', paragraphs: [
          'Shopify is hosted software. The platform operates the core infrastructure, security updates and much of the checkout. You pay a recurring platform fee and usually add paid apps as requirements grow. This reduces several technical responsibilities, but it also means working within Shopify’s product, checkout and pricing model.',
          'WooCommerce is an open-source commerce plugin for WordPress. You choose the host, theme, plugins, payment extensions and maintenance approach. That freedom can be valuable, especially for unusual content or integrations, but every additional moving part needs an owner. “Free software” is not the same as a free store.',
        ] },
        { type: 'comparison', caption: 'A practical comparison', headers: ['Decision', 'Shopify', 'WooCommerce'], rows: [
          ['Hosting and updates', 'Managed as part of the platform', 'Chosen and maintained by the store owner or supplier'],
          ['Initial setup', 'Often faster for standard commerce', 'Varies with WordPress, theme and plugin choices'],
          ['Customization', 'Strong within platform boundaries', 'Very broad, with corresponding maintenance responsibility'],
          ['Ongoing cost', 'Platform, apps and transaction-related costs', 'Hosting, licenses, development and maintenance'],
          ['Content publishing', 'Capable, commerce-first', 'Strong when editorial content is central'],
          ['Technical ownership', 'Lower infrastructure burden', 'More control and more responsibility'],
        ] },
        { type: 'section', id: 'israel', title: 'The Israeli requirements to validate first', paragraphs: [
          'Do not select a platform before confirming the exact payment gateway, invoicing system and shipping services you plan to use. Availability and quality differ by provider, and a connector existing in a marketplace does not guarantee that it supports every transaction type, refund flow or accounting requirement.',
          'Test Hebrew and RTL in the actual theme, including product variants, filters, search, account screens, transactional messages and any app-rendered interface. Also verify VAT display, invoice or receipt flow, local address fields, delivery rules, pickup options and support for the currencies and markets you intend to serve.',
          'For payments, document what happens on approval, rejection, cancellation, partial refund and duplicate callback. For fulfilment, document how an order reaches the warehouse or courier and how tracking returns to the customer. These edge cases matter more than the homepage theme.',
        ] },
        { type: 'list', title: 'Ask each potential implementation partner to demonstrate', items: [
          'A complete test order using the intended Israeli payment and invoicing setup',
          'Hebrew and mobile layouts for every important storefront and account state',
          'The process for refunds, cancellations, failed payments and stock corrections',
          'Who updates themes, plugins and apps—and how failures are detected',
          'A realistic monthly and annual cost including essential extensions and support',
        ] },
        { type: 'section', id: 'cost', title: 'Compare total cost, not the entry price', paragraphs: [
          'For Shopify, estimate the plan, payment-related charges relevant to the chosen setup, theme, essential apps, email or search tools, and development support. A low monthly plan can grow as separate apps are added for operational needs.',
          'For WooCommerce, estimate managed hosting, premium plugin renewals, backups, security, monitoring, development support and the cost of testing updates. Cheap hosting can become expensive when slow pages or outages affect sales. Managed WordPress providers such as uPress and broad hosting companies such as Hostinger represent different operating choices; evaluate support, backups and performance for your actual store.',
          'Use a two- or three-year view. Include internal time spent publishing products, resolving app conflicts, maintaining integrations and contacting support. The platform with the lower invoice is not always the platform with the lower business cost.',
        ] },
        { type: 'providers', title: 'Platforms and infrastructure mentioned in this guide', body: 'These are direct provider links for further evaluation. A recommendation should follow your requirements, not a referral arrangement.', providers: ['shopify', 'upress', 'hostinger', 'elementor'] },
        { type: 'section', id: 'fit', title: 'When each platform tends to fit', paragraphs: [
          'Shopify often fits a commerce-led business that wants a stable managed core, uses reasonably standard catalogue and fulfilment flows, and prefers to reduce infrastructure decisions. It is also attractive when a team needs a predictable admin experience and access to a large commerce ecosystem.',
          'WooCommerce often fits a business whose site is as much a content platform as a store, needs deep control over data or presentation, already operates WordPress well, or has custom requirements that are easier to own directly. It is a poor fit when nobody is accountable for maintenance.',
          'There are cases where neither is the best option. Wix may suit a smaller, straightforward catalogue when its Israeli payment and operational integrations meet the requirements. A custom commerce build is justified only when a distinctive business model creates enough value to offset the cost and responsibility.',
        ] },
        { type: 'serviceLink', service: 'ecommerce', title: 'Turn the comparison into a project decision', body: 'If you have a catalogue, current stack and operational requirements, I can help evaluate the fit and build or improve the store around them.', label: 'Explore e-commerce development' },
        { type: 'section', id: 'decision', title: 'A simple decision process', paragraphs: [
          'Write down the non-negotiable integrations, catalogue size, content needs, internal skills, expected order volume and who will maintain the system. Build a small proof around the riskiest local integration before committing to a full design.',
          'Then score both platforms on operating effort, customer experience, integration reliability, three-year cost and ability to change. The right answer is the one your business can operate confidently after the launch team leaves.',
        ] },
      ],
    },
    'business-website-cost-2026': {
      slug: 'business-website-cost-2026',
      metadata: {
        title: 'How Much Does a Business Website Cost in 2026? | Oz Digital',
        description: 'A practical guide to business website costs in 2026, including scope, content, design, technology, integrations, maintenance and budgeting.',
      },
      category: 'Websites',
      title: 'How much does a business website cost in 2026?',
      description: 'A useful budget starts with scope and business value—not a single price attached to the word “website.”',
      readingTime: '9 min read',
      publishedLabel: 'Updated September 2026',
      publishedDate: '2026-09-04',
      updatedDate: '2026-09-04',
      intro: [
        'Two websites with the same number of pages can require very different amounts of work. One may use established content and a standard template; the other may need positioning, original design, multilingual content, integrations and a careful migration from an existing site.',
        'Instead of quoting a misleading universal number, this guide shows what creates cost, how to define a realistic scope and how to compare proposals on the same basis.',
      ],
      blocks: [
        { type: 'callout', title: 'A better budgeting question', body: 'Ask what the website must change for the business, what work is required to achieve that, and what it will cost to own after launch.' },
        { type: 'section', id: 'scope', title: 'The six cost drivers', paragraphs: [
          'Strategy covers audience research, positioning, conversion goals and information architecture. Content covers writing, editing, translation, photography and migration. Design ranges from adapting a proven system to creating a distinctive interface. Development ranges from configuring a platform to building custom components and application behavior.',
          'Integrations add forms, CRM, scheduling, payments, analytics, email or internal systems. Quality and launch work includes responsive testing, accessibility, performance, redirects, search foundations, analytics verification and deployment. Each category can be small or substantial, which is why page count alone is a weak estimate.',
        ] },
        { type: 'comparison', caption: 'Typical scope bands—not fixed price quotes', headers: ['Project type', 'Usually includes', 'Main variable'], rows: [
          ['Focused landing page', 'One journey, concise content, form and analytics', 'Content readiness and custom design'],
          ['Business marketing site', 'Several services, about, proof, contact and CMS', 'Strategy, copy, language count and integrations'],
          ['Content-led site', 'Structured publishing, categories, search and migration', 'Content volume and editorial workflow'],
          ['Custom web experience', 'Unique interactions, data or authenticated features', 'Product complexity and backend requirements'],
          ['E-commerce site', 'Catalogue, checkout, payments and fulfilment', 'Products, operations and integrations'],
        ] },
        { type: 'section', id: 'platform', title: 'How the platform affects the budget', paragraphs: [
          'A platform can reduce implementation work when its standard model fits. Wix can bundle hosting and editing in one place. WordPress can support flexible publishing through a large ecosystem. Custom development can deliver greater control and performance for unusual requirements. None is automatically the cheapest once design, content, integrations and maintenance are included.',
          'Choose based on who will edit the site, what must connect to it, how distinctive the experience needs to be, what the security and uptime expectations are, and who will maintain the technical layer. Paying for unused flexibility is wasteful; forcing an important workflow into a limited template is also expensive.',
        ] },
        { type: 'providers', title: 'Common platform options to evaluate', body: 'These provider links are a starting point for comparison. The best fit depends on the scope and ownership model.', providers: ['wix', 'hostinger', 'elementor', 'upress'] },
        { type: 'section', id: 'proposal', title: 'What a useful proposal should make explicit', paragraphs: [
          'A serious proposal should identify deliverables, responsibilities, assumptions, revision boundaries, content inputs, supported devices and browsers, integrations, launch work and what happens after launch. It should say whether copywriting, translation, stock assets, licenses, hosting, maintenance and tax are included.',
          'Compare exclusions as carefully as totals. One proposal may include content workshops, technical SEO and migration; another may assume the client supplies final copy and handles redirects. Those are different products even if both are called a five-page website.',
        ] },
        { type: 'list', title: 'Prepare these inputs before requesting estimates', items: [
          'The primary audience and action you want each visitor to take',
          'A list of required pages, languages and content owners',
          'Examples of required forms, tools, payments or system integrations',
          'Brand assets and an honest assessment of content readiness',
          'The launch deadline and any event or campaign driving it',
          'Who will update the site and what support they expect afterward',
        ] },
        { type: 'section', id: 'ongoing', title: 'Budget beyond launch', paragraphs: [
          'Every site has ongoing costs: domain renewal, hosting or platform fees, licenses, backups, monitoring, security updates, content work and occasional development. The mix changes by stack. A hosted builder bundles more responsibilities; an open system exposes more choices; a custom application needs deliberate ownership.',
          'Reserve a modest improvement budget if the site has a revenue goal. After launch, analytics and real customer questions often reveal higher-value changes than the assumptions made during design. A website treated as a maintained business asset tends to outperform one treated as a finished brochure.',
        ] },
        { type: 'serviceLink', service: 'websites', title: 'Define the right website scope', body: 'I plan and build business websites with the platform selected around content, integrations, maintenance and commercial goals.', label: 'Explore website development' },
        { type: 'section', id: 'brief', title: 'The practical next step', paragraphs: [
          'Create a one-page brief with the business goal, users, required content, integrations, constraints and definition of success. Ask potential suppliers to challenge it and explain where complexity sits. A useful discovery conversation may reduce scope by revealing that one strong journey matters more than several weak pages.',
          'The most economical website is not necessarily the one with the smallest launch invoice. It is the one that solves the right problem, can be operated by the business and does not require avoidable rebuilding six months later.',
        ] },
      ],
    },
    'small-business-automations': {
      slug: 'small-business-automations',
      metadata: {
        title: '10 Automations That Save a Small Business Hours | Oz Digital',
        description: 'Ten practical small-business automations for leads, CRM, email, documents, invoices and back-office work, with guidance on value and risk.',
      },
      category: 'Automation',
      title: '10 automations that can save a small business hours every week',
      description: 'The best automation opportunities are usually repetitive, rules-based handoffs—not futuristic AI projects.',
      readingTime: '11 min read',
      publishedLabel: 'Updated September 2026',
      publishedDate: '2026-09-04',
      updatedDate: '2026-09-04',
      intro: [
        'Small businesses lose time in the gaps between tools: copying a lead from a form, reminding someone to follow up, renaming a document, checking whether an invoice was paid or rebuilding the same weekly report.',
        'The ten ideas below are deliberately practical. Each one should begin with a baseline—how often it happens, how long it takes and what errors cost—so the result can be measured instead of merely described as “smart.”',
      ],
      blocks: [
        { type: 'callout', title: 'A useful rule', body: 'Automate stable, frequent steps. Keep people responsible for judgment, sensitive communication and unusual exceptions.' },
        { type: 'section', id: 'lead-capture', title: '1. Capture and route every lead', paragraphs: [
          'When a form, ad platform or chat produces a lead, create or update the CRM record, tag the source, assign an owner and notify the right person. Validate phone and email fields before the record enters the pipeline.',
          'Measure response time, duplicate rate and the percentage of leads that receive a first action. Do not send an elaborate sales sequence until consent, source quality and ownership are clear.',
        ] },
        { type: 'section', id: 'follow-up', title: '2. Create follow-up tasks from pipeline status', paragraphs: [
          'A lead that changes stage can create a dated task, internal reminder or customer message. This removes the need to maintain a separate follow-up spreadsheet and makes neglected opportunities visible.',
          'Include a stop condition when the customer replies, opts out or the opportunity closes. Automation that keeps messaging after context changes harms trust.',
        ] },
        { type: 'section', id: 'appointments', title: '3. Prepare and follow up on appointments', paragraphs: [
          'A booking can create the calendar event, send preparation instructions, open a CRM activity and schedule a reminder. After the meeting, it can request notes or send the correct next-step template.',
          'Keep time zones, cancellations and rescheduling as first-class states. Duplicate calendar events are a common sign that the workflow was designed only for the happy path.',
        ] },
        { type: 'section', id: 'documents', title: '4. Generate routine documents from approved data', paragraphs: [
          'Proposals, onboarding forms, work orders and status summaries can be generated from a CRM or intake record. The workflow can save the file in the correct folder, apply a naming convention and notify an owner for review.',
          'Use templates and locked fields for legal or financial language. Generation should reduce copying, not silently invent commitments.',
        ] },
        { type: 'section', id: 'invoices', title: '5. Connect completed work to invoicing', paragraphs: [
          'When a project reaches an approved milestone, prepare an invoice request with customer, amount and reference data. A human can approve it before the accounting system sends anything. Payment status can then update the project or trigger a polite reminder.',
          'Financial workflows need idempotency: the same event must not create a second invoice. Log identifiers and test retries before enabling automatic actions.',
        ] },
        { type: 'section', id: 'support', title: '6. Triage incoming customer messages', paragraphs: [
          'Messages from email, forms or supported WhatsApp provider workflows can be classified by topic and urgency, attached to the right customer and placed in a shared queue. AI can assist with classification or a draft response, while a person handles sensitive or ambiguous cases.',
          'Use official APIs and approved providers for WhatsApp-related flows. Avoid fragile automation around personal accounts, and make consent and opt-out handling part of the design.',
        ] },
        { type: 'section', id: 'onboarding', title: '7. Coordinate customer onboarding', paragraphs: [
          'A signed agreement can trigger a checklist: create project folders, invite the customer, request missing assets, schedule the kickoff and create internal tasks. Each step should record completion so the team sees what is blocked.',
          'This is especially valuable when several people repeat the same setup for every customer. Start with a checklist that already works manually before automating it.',
        ] },
        { type: 'section', id: 'reporting', title: '8. Build recurring operating reports', paragraphs: [
          'Collect agreed metrics from sales, marketing, support or operations into one weekly summary. Highlight exceptions and missing data rather than flooding the team with another dashboard.',
          'Define each metric and its source. A fast automated report built on inconsistent definitions simply distributes confusion more efficiently.',
        ] },
        { type: 'section', id: 'data-sync', title: '9. Keep key records synchronized', paragraphs: [
          'When customer details, product status or project ownership changes in the system of record, update the systems that genuinely need it. Prefer one authoritative source and a clear direction of travel over uncontrolled two-way synchronization.',
          'Handle deletions, conflicting updates and API failures explicitly. Send failed records to a review queue instead of quietly losing them.',
        ] },
        { type: 'section', id: 'back-office', title: '10. Turn repetitive back-office intake into a queue', paragraphs: [
          'Attachments, spreadsheet rows and submitted forms can be renamed, checked, categorized and routed. AI-assisted extraction can pull structured fields from semi-structured documents, but low-confidence results should wait for review.',
          'This pattern works for supplier documents, expense evidence, applications and recurring operations. Measure minutes saved per item, correction rate and queue age.',
        ] },
        { type: 'providers', title: 'A common workflow layer', body: 'Make can connect many standard tools quickly. Custom API work is often preferable when logic, scale, security or reliability exceeds what a visual scenario should own.', providers: ['make'] },
        { type: 'section', id: 'prioritize', title: 'How to choose the first automation', paragraphs: [
          'List recurring tasks and score each on frequency, minutes per run, error cost, rule stability and implementation risk. A high-frequency fifteen-minute task with clear inputs may be a better first project than an impressive AI idea with uncertain outputs.',
          'Document the current baseline and a target such as reducing median lead response from four hours to fifteen minutes, or cutting weekly reconciliation from three hours to thirty minutes. Add monitoring, an owner and a manual fallback. If nobody knows when a workflow fails, it is not finished.',
        ] },
        { type: 'serviceLink', service: 'automation', title: 'Find the workflow with the clearest return', body: 'I map business processes, connect systems with Make or APIs, and add AI only where it reliably reduces real work.', label: 'Explore automation and AI services' },
      ],
    },
  },
  common: {
    homeLabel: 'Home',
    servicesLabel: 'Services',
    guidesLabel: 'Guides',
    contactLabel: 'Start a conversation',
    recommendedToolsLabel: 'Visit provider',
    affiliateDisclosure: 'Some provider links may become affiliate links in the future. If that happens, Oz Digital may receive compensation at no additional cost to you. Recommendations remain based on fit.',
    tableOfContents: 'In this guide',
  },
} as const satisfies RevenueDictionary
